// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf9Nmk5qv1EzSMcqXzwOnV6Yvgyf0lor0',
    appId: '1:222197983217:web:eae7ac37f117bd0029c650',
    messagingSenderId: '222197983217',
    projectId: 'tonkoh-bible-truth-revea-a7694',
    authDomain: 'tonkoh-bible-truth-revea-a7694.firebaseapp.com',
    databaseURL: 'https://tonkoh-bible-truth-revea-a7694-default-rtdb.firebaseio.com',
    storageBucket: 'tonkoh-bible-truth-revea-a7694.firebasestorage.app',
    measurementId: 'G-LJHF9GF1DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQFRQHFlLB4rk1Hc67_p7VHnlebrEyM-U',
    appId: '1:222197983217:android:12fe60ffe61a902a29c650',
    messagingSenderId: '222197983217',
    projectId: 'tonkoh-bible-truth-revea-a7694',
    databaseURL: 'https://tonkoh-bible-truth-revea-a7694-default-rtdb.firebaseio.com',
    storageBucket: 'tonkoh-bible-truth-revea-a7694.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLxShGpDWU66o4IJminHBmCOzxSbtBtCQ',
    appId: '1:222197983217:ios:6e423111dc0a791d29c650',
    messagingSenderId: '222197983217',
    projectId: 'tonkoh-bible-truth-revea-a7694',
    databaseURL: 'https://tonkoh-bible-truth-revea-a7694-default-rtdb.firebaseio.com',
    storageBucket: 'tonkoh-bible-truth-revea-a7694.firebasestorage.app',
    iosBundleId: 'com.tbtrapp.tonkohBibleTruthRevealers',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLxShGpDWU66o4IJminHBmCOzxSbtBtCQ',
    appId: '1:222197983217:ios:6e423111dc0a791d29c650',
    messagingSenderId: '222197983217',
    projectId: 'tonkoh-bible-truth-revea-a7694',
    databaseURL: 'https://tonkoh-bible-truth-revea-a7694-default-rtdb.firebaseio.com',
    storageBucket: 'tonkoh-bible-truth-revea-a7694.firebasestorage.app',
    iosBundleId: 'com.tbtrapp.tonkohBibleTruthRevealers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf9Nmk5qv1EzSMcqXzwOnV6Yvgyf0lor0',
    appId: '1:222197983217:web:7f6efa85b9f6f90e29c650',
    messagingSenderId: '222197983217',
    projectId: 'tonkoh-bible-truth-revea-a7694',
    authDomain: 'tonkoh-bible-truth-revea-a7694.firebaseapp.com',
    databaseURL: 'https://tonkoh-bible-truth-revea-a7694-default-rtdb.firebaseio.com',
    storageBucket: 'tonkoh-bible-truth-revea-a7694.firebasestorage.app',
    measurementId: 'G-488HXF2SLG',
  );
}
