package com.tbtrapp.call

import com.google.firebase.database.IgnoreExtraProperties

/**
 * Type of call.
 */
enum class CallType { AUDIO, VIDEO }

/**
 * Current state of a call session, written to Firebase RTDB at
 *   calls/{callId}/state
 * so both sides (and OneSignal push payloads) can agree on where the call is.
 */
enum class CallState { RINGING, ACCEPTED, DECLINED, ENDED, MISSED, BUSY }

/**
 * The root call document, stored at: calls/{callId}
 *
 * callId should be generated by the CALLER as a random push key
 * (FirebaseDatabase push().key) so both sides share one id.
 *
 * FIX: renamed callerUid -> callerId and calleeUid -> calleeId.
 *
 * Firebase serializes this data class using its Kotlin property names as
 * the JSON keys. Two other places in the codebase already read the call
 * document expecting those exact keys:
 *   - OngoingCallActivity.onCreate(): snapshot.child("callerId") / "calleeId"
 *   - FirebaseSignalingRepository.startListeningForIncomingCalls():
 *     snapshot.child("calleeId") and .orderByChild("calleeId")
 *
 * With the old callerUid/calleeUid names, both of those reads would
 * silently come back null/empty for any call actually created via
 * CallSession — theirUid would be blank in OngoingCallActivity, and the
 * incoming-call query would never match anyone.
 *
 * If you have another file that constructs CallSession(callerUid = ...,
 * calleeUid = ...) by named argument, update it to callerId / calleeId
 * as well — this file alone won't fix a call site still using the old
 * names.
 */
@IgnoreExtraProperties
data class CallSession(
    val callId: String = "",
    val callerId: String = "",
    val callerName: String = "",
    val callerPhotoUrl: String = "",
    val calleeId: String = "",
    val type: String = CallType.VIDEO.name,   // "AUDIO" or "VIDEO"
    val state: String = CallState.RINGING.name,
    val createdAt: Long = 0L
)

/**
 * SDP offer/answer payload, stored at:
 *   calls/{callId}/offer   and   calls/{callId}/answer
 */
@IgnoreExtraProperties
data class SdpPayload(
    val type: String = "",   // "offer" or "answer"
    val sdp: String = ""
)

/**
 * A single ICE candidate, stored under:
 *   calls/{callId}/candidates/{callerUid or calleeUid}/{pushId}
 *
 * We keep caller and callee candidates in separate sub-nodes so each
 * side only listens to the OTHER side's candidates, never its own.
 */
